# fly.toml app configuration file generated for magic-awaaaay on 2023-09-11T14:38:33+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "magic-awaaaay"
primary_region = "syd"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
